import { useEffect, useState, useCallback, useMemo } from "react";

// Demo data
const demoVolunteers = [
  {
    id: 1,
    name: "Nguyễn Văn An",
    email: "nguyen.van.an@email.com",
    phone: "0901234567",
    role: "event_coordinator",
    status: "active",
    experience: "experienced",
    availability: "weekends",
    location: "Hanoi",
    skills: ["event_management", "communication", "leadership"],
    joinDate: "2024-01-15",
    created_at: "2024-01-15T10:30:00Z",
    lastActive: "2024-09-08",
    completedTasks: 15,
    rating: 4.8
  },
  {
    id: 2,
    name: "Trần Thị Bình",
    email: "tran.thi.binh@email.com",
    phone: "0912345678",
    role: "community_outreach",
    status: "active",
    experience: "intermediate",
    availability: "flexible",
    location: "Ho Chi Minh",
    skills: ["communication", "social_media", "outreach"],
    joinDate: "2024-02-20",
    created_at: "2024-02-20T14:15:00Z",
    lastActive: "2024-09-09",
    completedTasks: 12,
    rating: 4.6
  },
  {
    id: 3,
    name: "Lê Văn Cường",
    email: "le.van.cuong@email.com",
    phone: "0923456789",
    role: "fundraising",
    status: "pending",
    experience: "beginner",
    availability: "weekdays",
    location: "Da Nang",
    skills: ["sales", "networking"],
    joinDate: "2024-08-30",
    created_at: "2024-08-30T09:20:00Z",
    lastActive: "2024-09-05",
    completedTasks: 2,
    rating: 4.2
  },
  {
    id: 4,
    name: "Phạm Thị Dung",
    email: "pham.thi.dung@email.com",
    phone: "0934567890",
    role: "admin_support",
    status: "active",
    experience: "expert",
    availability: "weekdays",
    location: "Hanoi",
    skills: ["administration", "data_entry", "organization"],
    joinDate: "2023-11-10",
    created_at: "2023-11-10T16:45:00Z",
    lastActive: "2024-09-09",
    completedTasks: 28,
    rating: 4.9
  },
  {
    id: 5,
    name: "Hoàng Văn Em",
    email: "hoang.van.em@email.com",
    phone: "0945678901",
    role: "technical_support",
    status: "inactive",
    experience: "experienced",
    availability: "limited",
    location: "Hanoi",
    skills: ["programming", "troubleshooting", "training"],
    joinDate: "2024-03-05",
    created_at: "2024-03-05T11:30:00Z",
    lastActive: "2024-08-15",
    completedTasks: 8,
    rating: 4.4
  },
  {
    id: 6,
    name: "Vũ Thị Giang",
    email: "vu.thi.giang@email.com",
    phone: "0956789012",
    role: "event_coordinator",
    status: "active",
    experience: "intermediate",
    availability: "weekends",
    location: "Ho Chi Minh",
    skills: ["event_planning", "coordination", "teamwork"],
    joinDate: "2024-04-12",
    created_at: "2024-04-12T13:20:00Z",
    lastActive: "2024-09-08",
    completedTasks: 11,
    rating: 4.7
  },
  {
    id: 7,
    name: "Đỗ Văn Hải",
    email: "do.van.hai@email.com",
    phone: "0967890123",
    role: "community_outreach",
    status: "pending",
    experience: "beginner",
    availability: "flexible",
    location: "Da Nang",
    skills: ["communication", "research"],
    joinDate: "2024-09-01",
    created_at: "2024-09-01T08:15:00Z",
    lastActive: "2024-09-07",
    completedTasks: 1,
    rating: 4.0
  },
  {
    id: 8,
    name: "Bùi Thị Hoa",
    email: "bui.thi.hoa@email.com",
    phone: "0978901234",
    role: "fundraising",
    status: "active",
    experience: "experienced",
    availability: "weekdays",
    location: "Hanoi",
    skills: ["fundraising", "donor_relations", "event_planning"],
    joinDate: "2023-12-18",
    created_at: "2023-12-18T15:30:00Z",
    lastActive: "2024-09-09",
    completedTasks: 22,
    rating: 4.8
  },
  {
    id: 9,
    name: "Ngô Văn Ích",
    email: "ngo.van.ich@email.com",
    phone: "0989012345",
    role: "admin_support",
    status: "active",
    experience: "intermediate",
    availability: "weekdays",
    location: "Ho Chi Minh",
    skills: ["data_analysis", "reporting", "coordination"],
    joinDate: "2024-05-20",
    created_at: "2024-05-20T10:45:00Z",
    lastActive: "2024-09-08",
    completedTasks: 9,
    rating: 4.5
  },
  {
    id: 10,
    name: "Lý Thị Kim",
    email: "ly.thi.kim@email.com",
    phone: "0990123456",
    role: "technical_support",
    status: "inactive",
    experience: "expert",
    availability: "limited",
    location: "Da Nang",
    skills: ["web_development", "database", "training"],
    joinDate: "2024-01-30",
    created_at: "2024-01-30T12:00:00Z",
    lastActive: "2024-07-20",
    completedTasks: 18,
    rating: 4.6
  }
];


export default function VolunteerManagementPage() {
  
  return (
    <div>
      
    </div>
  )
}